name: Auto Create PR

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main
      - develop

  pull_request:
    types:
      - closed
    branches-ignore:
      - main

jobs:
  check-if-renovate:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest

    outputs:
      skip: ${{ steps.check_renovate.outputs.skip }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check for renovate_bot commits
        id: check_renovate
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          echo "Commit author: $AUTHOR"
          skip=false
          if [ "$AUTHOR" = "renovate[bot]" ]; then
            echo "Commit made by renovate_bot. Skipping PR changing."
            skip=true
          else
            skip=false
          fi
          echo "skip=$skip" >> "$GITHUB_OUTPUT"

  create-or-update-pr:
    if: ${{ needs.check-if-renovate.outputs.skip != 'true' }}
    runs-on: ubuntu-latest
    needs: check-if-renovate

    permissions:
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit type
        id: commit_type
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Get PR tittle and body
        id: format_message
        env:
          EVENT_NAME: ${{ github.event_name }}
          TYPE: ${{ steps.commit_type.outputs.release_type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TITLE=${GITHUB_REF#refs/heads/}
          echo "Current branch is $TITLE"
          SKIP_CHANGE=$(./scripts/getPR.sh "$TYPE" "$TITLE")
          echo "Change type is $TYPE"
          echo "Should I skip the change? $SKIP_CHANGE"
          echo "skip_change=$SKIP_CHANGE" >> "$GITHUB_OUTPUT"

      - name: Create or edit pull request for current branch
        if: ${{ steps.format_message.outputs.skip_change != 'skip' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
        run: |
          current_branch=${GITHUB_REF#refs/heads/}
          pr_count=$(gh pr list --state open --head "$current_branch" | wc -l)
          if [ "$pr_count" -gt 0 ]; then
            echo "Already exist a pr, trying to update~"
            gh pr edit --body-file ./pr_body.md
          else
            echo "Not found pr about current branch, starting to create a new one~"
            gh pr create --reviewer "$OWNER" --base "develop" --draft --fill --body-file ./pr_body.md
          fi

  create-develop-pr:
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changelog
        id: tag_action
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Create pull request to develop
        env:
          OWNER: ${{ github.repository_owner }}
          BODY: ${{ steps.tag_action.outputs.changelog }}
          TAG: ${{ steps.tag_action.outputs.new_tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch develop
          git pull
          current_branch=${GITHUB_REF#refs/heads/}
          pr_count=$(gh pr list --state open --head "$current_branch" | wc -l)
          if [ "$pr_count" -gt 0 ]; then
            echo "Already exist a pr, trying to update~"
            gh pr edit --body "$BODY"
          else
            echo "Not found pr about develop, starting to create a new one~"
            gh pr create --reviewer "$OWNER" --base "main" --draft --title "Prepare for $TAG" --body "$BODY"
          fi
