name: Bump & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version-and-release:
    name: Bump version & release
    #    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true

      #      - name: Build project
      #        run: |
      #          pnpm build
      #          tar -czvf ./pages.tar.gz ./next
      #          zip -r -q ./pages.zip ./next

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.tag_version.outputs.changelog}}
          tag_name: ${{steps.tag_version.outputs.new_tag}}
#          files: |
#            ./pages.tar.gz
#            ./pages.zip
